# Generated by Django 6.0.1 on 2026-01-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('owner', 'Owner')], default='guest', help_text='Define si el usuario es propietario de propiedades o consumidor/huésped', max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
