# Generated by Django 6.0.1 on 2026-02-02 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(db_index=True, help_text='UUID de la reservación en MongoDB', max_length=255, verbose_name='ID de Reservación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('currency', models.CharField(default='USD', help_text='Código ISO 4217 (USD, EUR, etc.)', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria'), ('other', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago'), ('manual', 'Manual')], max_length=20, verbose_name='Pasarela de Pago')),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, help_text='ID del pago en la pasarela (Stripe, PayPal, etc.)', max_length=255, null=True, verbose_name='ID de Pago en Pasarela')),
                ('gateway_response', models.JSONField(blank=True, help_text='Respuesta completa de la pasarela de pago', null=True, verbose_name='Respuesta de Pasarela')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, help_text='Información adicional del pago', null=True, verbose_name='Metadatos')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Error')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallo')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reembolso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Tarjeta'), ('bank_account', 'Cuenta Bancaria')], max_length=20, verbose_name='Tipo de Pago')),
                ('last_four', models.CharField(max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('brand', models.CharField(blank=True, help_text='Visa, Mastercard, Amex, etc.', max_length=20, verbose_name='Marca')),
                ('expiry_month', models.IntegerField(blank=True, null=True, verbose_name='Mes de Expiración')),
                ('expiry_year', models.IntegerField(blank=True, null=True, verbose_name='Año de Expiración')),
                ('gateway_token', models.CharField(help_text='Token proporcionado por la pasarela de pago', max_length=255, verbose_name='Token de Pasarela')),
                ('gateway', models.CharField(help_text='Stripe, PayPal, etc.', max_length=20, verbose_name='Pasarela')),
                ('is_default', models.BooleanField(default=False, verbose_name='Método Predeterminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Cargo'), ('refund', 'Reembolso'), ('void', 'Anulación'), ('authorization', 'Autorización'), ('capture', 'Captura')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('status', models.CharField(choices=[('success', 'Exitosa'), ('failed', 'Fallida'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Transacción en Pasarela')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Error')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('response_data', models.JSONField(blank=True, help_text='Respuesta completa de la pasarela', null=True, verbose_name='Datos de Respuesta')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la transacción', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation_id', 'status'], name='payments_reserva_36243a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_payment_id'], name='payments_gateway_e04247_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payment_met_user_id_a6fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['gateway_token'], name='payment_met_gateway_cbad34_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment', 'transaction_type'], name='transaction_payment_d08408_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_transaction_id'], name='transaction_gateway_cb205b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
    ]
